services:
  fastapi-app:
    build: .
    container_name: TWA
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    networks:
      - twa-network
    # 필요시 의존성이 있다면 아래처럼 depends_on 등 추가
    # depends_on:
    #   - some-other-service

    # redis 연결
  redis:
    image: "redis:latest"
    container_name: redis-twa
    ports:
      - "6379:6379"
    networks:
      - twa-network
networks:
  twa-network:
    driver: bridge